### ISSUE TITLE
Fatal error: Class 'Location\Coordinate' not found 

### ISSUE THREAD

**Issue by Logistix84** [mjaschen/phpgeo#14]
Hi. Thanks for project. Very nice and powerfull instrument! But i have some trouble:

<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require_once "autoload.php";

use Location\Coordinate;
use Location\Distance\Vincenty;

$coordinate1 = new Coordinate(19.820664, -155.468066); // Mauna Kea Summit
$coordinate2 = new Coordinate(20.709722, -156.253333); // Haleakala Summit

$calculator = new Vincenty();

echo $calculator->getDistance($coordinate1, $coordinate2);
?>

GOT:
Fatal error: Class 'Location\Coordinate' not found in /var/www/html/phpgeo/vendor/index.php on line 8

PHP Version 5.6.21

**Comment by mjaschen** [comment]
Hi,

it seems that something is wrong with the autoloader.

Please try to reproduce if the following works:

1. `composer require mjaschen/phpgeo`
2. save [this file](https://gist.github.com/mjaschen/4305ab1251615660328d6d714d01e7f0) to the current directory as `test.php`
3. run `php test.php`

The script should print `128130.85` to the terminal.
