### ISSUE TITLE
Add functionality to move Coordinates

### ISSUE THREAD

**Issue by corneyl** [mjaschen/phpgeo#19]
It would be nice to see some sort of function with which a coordinate could be moved in a certain direction and distance, e.g.:
```
$point =new Coordinate(19.820664, -155.468066);
$point->move(45, 5000); // Move $point to the east over 5 km
```

**Comment by mjaschen** [comment]
Hi!

That functionality is already implemented.

It's possible to calculate a destination point for a given coordinate, a bearing angle, and a distance:

```php
<?php
use Location\Bearing\BearingEllipsoidal;
use Location\Bearing\BearingSpherical;
use Location\Coordinate;
use Location\Formatter\Coordinate\DecimalDegrees;

$berlin = new Coordinate(52.5, 13.5);

$bearing = new BearingEllipsoidal();

$destination = $bearing->calculateDestination($berlin, 153, 56100);

echo "Destination: " . $destination->format(new DecimalDegrees()) . PHP_EOL;
```

Here's the link to the documentation: https://phpgeo.marcusjaschen.de/#_destination_point_for_given_bearing_and_distance

**Comment by corneyl** [comment]
Great! I think I looked for the wrong terms in the readme, sorry.

**Comment by mjaschen** [comment]
> I think I looked for the wrong terms in the readme, sorry.

No problem :-)
