### ISSUE TITLE
Distance calculation

### ISSUE THREAD

**Issue by markus-dark-green** [mjaschen/phpgeo#22]
Sorry for the newbee question but when i am using the Distance calculation it provides me some false values. Went through the documentation but could not find some hint.

this is the function call:
$p1 = new \Location\Coordinate($point1_lat,$point1_long);
$p2 = new \Location\Coordinate($point2_lat,$point2_long);
$meters = $p1->getDistance($p2, new \Location\Distance\Vincenty());

and the result (sorry for the json encapsulation) is:

"distance": "4597208.7 Location\\Coordinate Object\n(\n    [lat:protected] => 16.1398995\n    [lng:protected] => 48.0313793\n    [ellipsoid:protected] => Location\\Ellipsoid Object\n        (\n            [name:protected] => World Geodetic System  1984\n            [a:protected] => 6378137\n            [f:protected] => 298.257223563\n        )\n\n)\n Location\\Coordinate Object\n(\n    [lat:protected] => 48.4664936\n    [lng:protected] => 16.3988242\n    [ellipsoid:protected] => Location\\Ellipsoid Object\n        (\n            [name:protected] => World Geodetic System  1984\n            [a:protected] => 6378137\n            [f:protected] => 298.257223563\n        )\n\n)\n"

is it a bug or is there a need to set unit system or is it just "stupid me"

**Comment by mjaschen** [comment]
Hi,

it seems that one of the two points has latitude and logitude values swapped.

From your example:

p1: lat=16.1398995, lng=48.0313793
p2: lat=48.4664936, lng=16.3988242

I think this issue will magically disappear if you swap the lat/lng values ;-)

Marcus

**Comment by markus-dark-green** [comment]
ohhhh so option 3  "me stupid"  sorry within the project i didnt see the forest cause of the many trees
