### ISSUE TITLE
Coordinate class naming

### ISSUE THREAD

**Issue by omissis** [mjaschen/phpgeo#26]
Hi, I was doing a little bit of domain research for a side project of mine, and I noticed your library: it looks nice! :) 
While reading the code, I noticed the "Coordinate" class and wondered if it shouldn't be named "Coordinates" (plural) as it represents a pair of coordinates(latitude and longitude, plus an ellipsoid).
Sorry for opening an issue for a single character, but I thought it could've been a possible item for the next major release.
Thanks!

**Comment by mjaschen** [comment]
Hi! 

Thanks for your comment. I thought a lot about the naming of the class myself and came to the conclusion to change it into something more common. My current favorite name is *Point* :-)

**Comment by omissis** [comment]
I see.. I definitely see a use for a Point class(as well as other shapes, such a Polyline and a Radius, for example), but I'd keep coordinates within those. jm2c ofc :)
Thanks for the quick reply! :)

**Comment by bmeynell** [comment]
Stellar library @mjaschen! 💪 
Chiming in because I love these types of discussions because I always learn something.

@omissis: Thoughts on below?
- `Point(float $position)`
- `PointPair(Point $latitude, Point $longitude)`
- `Coordinate(PointPair $points, Ellipsoid $ellipsoid = null)`

I'm 👎 for `Coordinates` (plural) because that would imply a _collection_ of `Coordinate` objects (to me, anyway).

**Comment by mjaschen** [comment]
Hi,

I just pushed the first commit to the [4.0 milestone](https://github.com/mjaschen/phpgeo/tree/milestone/4.0). The `Coordinate` class was renamed to `Point`. I don't have a due date for this milestone yet, probably sometime later in 2020.

**Comment by omissis** [comment]
@bmeynell sorry to get to answer your question so late! I'd be more for `Coordinates` as it's how someone would commonly use the term (think telling someone "tell me your coordinates": the result will be made of a latitude and a longitude). I understand the "Coordinates make me think of an array of Coordinate" kind of thinking, but I would dispute that's how (some/most) programmers think(so there's a clear bias): that's not necessarily bad(the library is for programmers after all), but it's not how the term is used in its original context.
