### ISSUE TITLE
Very important to find the polygon area by points. I can do?

### ISSUE THREAD

**Issue by chelkaz** [mjaschen/phpgeo#28]
Example Google Maps Area Calculator - https://www.daftlogic.com/projects-google-maps-area-calculator-tool.htm

**Comment by paulvl** [comment]
@chelkaz Actually you can the get perimeter of a Polygon using getPerimeter method, the area method needs a fix, by the time I write the Polygon Class I was unable to properly calculate the right value, if you do, please make a pull request if you know how to properly calculate it please add some sources and I'll be happy to implement it.

**Comment by chelkaz** [comment]
- Working - https://github.com/alexpechkarev/geometry-library

- method \GeometryLibrary\SphericalUtil::computeArea( $LatLng )

- I tested! Good Work!

**Comment by mjaschen** [comment]
You're able to calculate a polygon area now with the `getArea()` method. Please note that the result is somewhat inaccurate, but the error should be clearly below 1 %.
