### ISSUE TITLE
Polygon getArea method

### ISSUE THREAD

**Issue by felixveysseyre** [mjaschen/phpgeo#29]
Hello,

First thank you for this awesome library !

I am trying to compute the area of a polygon.
Looking at the implementation of you `Polygon` class, there is a `getArea` method. Looking at the annotation, the method is giving false results.

It is still true ? Do you have any idea when it will be fixed ?

Best,

**Comment by mjaschen** [comment]
Hi!

I'm still looking for an polygon area calculation algorithm which satisfies the following requirements:

- works for concave and convex polygons
- supports ellipsoids (e. g. “WGS-84”) and does not just use simple spherical coordinates
- _(optional)_ works for polygons which cross the -180°/+180° longitude boundary (once or more than once)

Unfortunately I didn't find such an algorithm yet. The current implementation was not implemented by me (was merged via a pull request some time ago).

Marcus

**Comment by felixveysseyre** [comment]
Thanks @mjaschen !

Got it !
I implemented my own algorithm before finding your library, but I think It only verify the first point of your list. Otherwise I would have been happy to contribute :)

Do you know why the area is 'wrong' ? Is it only because the current implementation use a spherical model instead of an ellipsoid one ?

**Comment by mjaschen** [comment]
I don't remember what exactly was wrong with the algorithm, but IIRC some test calculations lead to wrong results so I added the warning.

You're invited to create a pull request with your algorithm! (It's not a big problem if the support for ellipsoids is missing - we'll annotate the method documentation then).


Thanks!

**Comment by felixveysseyre** [comment]
I have implemented a new method and after some testing, the results look good.

I have created the pull request https://github.com/mjaschen/phpgeo/pull/31.
