### ISSUE TITLE
Given a point and a distance, is it possible to compute the corresponding extent ?

### ISSUE THREAD

**Issue by felixveysseyre** [mjaschen/phpgeo#30]
Hello,

I am trying to compute the extent `((latMin, latMax), (lngMin, lngMax))`, from a point (`Coordinate` object) and a distance.

Is there an easy way to do that ? I am not familiar with GPS coordinates yet.

Thank for your time.

**Comment by mjaschen** [comment]
What do you mean with “extend”? Does the following sketch show the wanted values of `((latMin, latMax), (lngMin, lngMax))`?

![](https://static.marcusjaschen.de/dump/images/IMG_1894_20170630_082548.JPG)

**Comment by felixveysseyre** [comment]
Yes, you correctly understood what I meant.

Here is another schema if needed: 
![extent](https://user-images.githubusercontent.com/4909259/27726179-99dc4f70-5d79-11e7-8511-891106d468b9.png)

**Comment by mjaschen** [comment]
It should be easy to do using [destination point calculation](https://phpgeo.marcusjaschen.de/#_destination_point_for_given_bearing_and_distance):

```php
<?php

use Location\Bearing\BearingEllipsoidal;
use Location\Coordinate;

require_once __DIR__ . '/vendor/autoload.php';

$berlin   = new Coordinate(52.5, 13.5);
$distance = 10000; // 10 km

$bearingEllipsoidal = new BearingEllipsoidal();

$northernMost = $bearingEllipsoidal->calculateDestination($berlin, 0, $distance);
$easternMost  = $bearingEllipsoidal->calculateDestination($berlin, 90, $distance);
$southernMost = $bearingEllipsoidal->calculateDestination($berlin, 180, $distance);
$westernMost  = $bearingEllipsoidal->calculateDestination($berlin, 270, $distance);

printf(
    'latMax=%f, latMin=%f, lngMax=%f, lngMin=%f%s',
    $northernMost->getLat(),
    $southernMost->getLat(),
    $easternMost->getLng(),
    $westernMost->getLng(),
    PHP_EOL
);

// verify the results:

$distCalc = new \Location\Distance\Vincenty();

printf(
    'dN=%f, dS=%f, dE=%f, dW=%f%s',
    $berlin->getDistance($northernMost, $distCalc),
    $berlin->getDistance($southernMost, $distCalc),
    $berlin->getDistance($easternMost, $distCalc),
    $berlin->getDistance($westernMost, $distCalc),
    PHP_EOL
);
```

The code above will produce the output below:

```
latMax=52.589865, latMin=52.410133, lngMax=13.647253, lngMin=13.352747
dN=10000.000000, dS=10000.000000, dE=10000.000000, dW=10000.000000
```

**Comment by felixveysseyre** [comment]
Thanks @mjaschen, It works like a charm !
