### ISSUE TITLE
Formatter returns too many decimals.

### ISSUE THREAD

**Issue by WeeRuz** [mjaschen/phpgeo#40]
I want to use PHPGeo for simplifying lines in geojson files.

PHP has a precision set to 8 (Leaving 6 decimals for the coordinates)

I add points to a new Polyline with addPoint and new Coordinate.

`$line = new Polyline;`
` foreach ($feature['geometry']['coordinates'] as $coordA){`
`      $line->addPoint(new Coordinate($coordA[1],$coordA[0]));`
`}`

I.e. the first coordinates from $feature['geometry']['coordinates'] are 
Lng: 15.640289
Lat: 60.604169

For debugging I'm outputting to my html with:
`$formatter = new GeoJSON;`
`echo var_dump($line->getPoints()[0]).'<br>';`
`echo $line->format(new GeoJSON()).'<br>';`
The var dump on the points shows that the Polyline does indeed only have 6 decimals.
But the echo on the results from the format shows Lng and Lat with this amount of decimals:
Lng: 15.6402892857124840020333067514002323150634765625
Lat: 60.6041694346744890253830817528069019317626953125

Which defeats the whole purpose of my simplification goal. As I save more bandwidth by just removing decimals. I don't want precision on subatomic levels.

Edit: Fixed some typos. Was in a hurry when I wrote it.

**Comment by WeeRuz** [comment]
Hi, thanks for looking into this. I was able to quick fix it by altering the source code of PHPGeo. In Location/Formatter/PolyLine/GeoJSON.php on line 36 I made sure the `$point->getLng()` and `$point->getLat()` gets formatted to 6 decimals with number_format.

`$points[] = [$point->getLng(), $point->getLat()];`
To
`$points[] = [number_format($point->getLng(),6), number_format($point->getLat(),6)];`


**This is a quick fix and most likely not the optimal fix.** (For people coming here with the same problem) 

Thanks for a great library otherwise. Does exactly what I want it to do ( except the above bug ). 12mb too 2.8 mb by removing decimals and 2.8 mb to 900 kb by simplifying.

**Comment by WeeRuz** [comment]
Okay after some fiddling I realized there is nothing wrong with your functions (did and echo on $points->getLng() ). The decimals get added by PHP's json_encode. I mentioned I added and ini_set precision to my code but an serialize_precision ini_set is needed also. 
http://php.net/manual/en/function.json-encode.php

So I added the serialize_precision to my code and now it works as intended. Maybe you could update the docs so it mentions that you can control the amount of decimals in outputted GeoJson by using serialize_precision.
`ini_set('serialize_precision',8);` 
8 gives 6 decimals as it counts the whole numbers to.  Works for me but may need altering for other uses.

**Comment by mjaschen** [comment]
Hi,

thanks for the update. I think, it's the best if that behaviour stays unchanged and is mentioned clearly in the documentation. I'll update the docs accordingly.

**Comment by mjaschen** [comment]
[Docs are updated](https://phpgeo.marcusjaschen.de/#_geojson_2)
