### ISSUE TITLE
composer error 

### ISSUE THREAD

**Issue by tamer-dahdul** [mjaschen/phpgeo#41]
- The requested package mjaschen/phpgeo No version set (parsed as 1.0.0) is
satisfiable by mjaschen/phpgeo[No version set (parsed as 1.0.0)] but these confl
ict with your requirements or minimum-stability.

**Comment by mjaschen** [comment]
Hi,

can you explain what you're doing? It'd be helpful if you share your `composer.json` and the command you're trying to run.

**Comment by tamer-dahdul** [comment]
i am trying to install the library using composer 

composer require mjaschen/phpgeo

my composer.json is the same as in the library

**Comment by tamer-dahdul** [comment]
i have php 7.0

**Comment by tamer-dahdul** [comment]
`{
    "name": "mjaschen/phpgeo",
    "description": "Simple Geo Library",
    "keywords": [
        "distance",
        "area",
        "coordinate",
        "geo",
        "gis",
        "bounds",
        "ellipsoid",
        "calculation",
        "polyline",
        "polygon",
        "geofence",
        "simplify",
        "length",
        "vincenty",
        "haversine",
        "bearing",
        "projection",
        "gps",
        "earth",
        "track",
        "point"
    ],
    "homepage": "https://phpgeo.marcusjaschen.de/",
    "type": "library",
    "license": "MIT",
    "authors": [
        {
            "name": "Marcus Jaschen",
            "email": "mjaschen@gmail.com",
            "homepage": "https://www.marcusjaschen.de/"
        }
    ],
    "support" : {
        "email" : "mjaschen@gmail.com"
    },
    "require": {
        "php": ">=7.0"
    },
    "autoload": {
        "psr-0": {
            "Location": "src/"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "~6.0",
        "vimeo/psalm": "^1.0",
        "jakub-onderka/php-parallel-lint": "^1.0",
        "squizlabs/php_codesniffer": "^3.2",
        "phpmd/phpmd": "^2.6"
    },
    "scripts": {
        "ci:lint": "./vendor/bin/parallel-lint src",
        "ci:psalm": "./vendor/bin/psalm",
        "ci:sniff": "./vendor/bin/phpcs --standard=codesniffer_rules.xml src || true",
        "ci:coding-standards": "./vendor/bin/phpmd src text cleancode,codesize,design,naming,unusedcode || true",
        "ci:tests": "./vendor/bin/phpunit tests/",
        "ci:static": [
            "@ci:lint",
            "@ci:psalm",
            "@ci:sniff",
            "@ci:coding-standards"
        ],
        "ci:dynamic": [
            "@ci:tests"
        ],
        "ci": [
            "@ci:static",
            "@ci:dynamic"
        ]
    }
}
`

**Comment by tamer-dahdul** [comment]
{
    "name": "mjaschen/phpgeo",
    "description": "Simple Geo Library",
    "keywords": [
        "distance",
        "area",
        "coordinate",
        "geo",
        "gis",
        "bounds",
        "ellipsoid",
        "calculation",
        "polyline",
        "polygon",
        "geofence",
        "simplify",
        "length",
        "vincenty",
        "haversine",
        "bearing",
        "projection",
        "gps",
        "earth",
        "track",
        "point"
    ],
    "homepage": "https://phpgeo.marcusjaschen.de/",
    "type": "library",
    "license": "MIT",
    "authors": [
        {
            "name": "Marcus Jaschen",
            "email": "mjaschen@gmail.com",
            "homepage": "https://www.marcusjaschen.de/"
        }
    ],
    "support" : {
        "email" : "mjaschen@gmail.com"
    },
    "require": {
        "php": ">=7.0"
    },
    "autoload": {
        "psr-0": {
            "Location": "src/"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "~6.0",
        "vimeo/psalm": "^1.0",
        "jakub-onderka/php-parallel-lint": "^1.0",
        "squizlabs/php_codesniffer": "^3.2",
        "phpmd/phpmd": "^2.6"
    },
    "scripts": {
        "ci:lint": "./vendor/bin/parallel-lint src",
        "ci:psalm": "./vendor/bin/psalm",
        "ci:sniff": "./vendor/bin/phpcs --standard=codesniffer_rules.xml src || true",
        "ci:coding-standards": "./vendor/bin/phpmd src text cleancode,codesize,design,naming,unusedcode || true",
        "ci:tests": "./vendor/bin/phpunit tests/",
        "ci:static": [
            "@ci:lint",
            "@ci:psalm",
            "@ci:sniff",
            "@ci:coding-standards"
        ],
        "ci:dynamic": [
            "@ci:tests"
        ],
        "ci": [
            "@ci:static",
            "@ci:dynamic"
        ]
    }
}

**Comment by mjaschen** [comment]
IMHO, it doesn't make a lot of sense to use the library's `composer.json` for your project. Or is there a reason why you'd like to install *phpgeo* as a requirement to *phpgeo*?

I bet everything will work fine if you use a clean `composer.json` (or no `composer.json` at all) and then run `composer require mjaschen/phpgeo`.

**Comment by tamer-dahdul** [comment]
it's working fine now 
Thanks
