### ISSUE TITLE
Calculation is wrong.

### ISSUE THREAD

**Issue by v920749** [mjaschen/phpgeo#5]
I tried a straight actual GPS track from real device and calculated distance to be 128Km and by processing each coordinate individually using polyline method it comes out to be 97.2

**Comment by mjaschen** [comment]
Hi,

can you provide me the GPS track so that I can verify the calculation?

Marcus

**Comment by v920749** [comment]
Hi,

Thanks for replying.

Attached is csv file of real track data for one of my device.

Total distance traveled is confirmed to be  > 135 Km You can check the
distance between first coordinate and last coordinate which is greater that
the total track length as per track getdistance.

Using track it comes out to be 97.2 KM with vincenty.

I tried to debug a bit and added echo to steps difference and I observed
that step distance was only upto three decimal places. I tried setting
precision in PHP.ini to 50 but still same. I have a feeling that this might
be summing up and causing the error

Thanks again for replying. Let me know if I can provide anything else for a
solution.

Regards

*Amit Nagpal*
IT Consultant
Shah Satnam Ji Research & Development Foundation.
Sirsa
+91.822.209.7787
-- Like a shadow, I am and I am not.

**Comment by mjaschen** [comment]
Hi, 

the CSV file didn't make it through Github's email gateway ;-) Can you create a [Gist](https://gist.github.com) for it?

Marcus

**Comment by v920749** [comment]
Ohh... its first time I am reporting an issue on Github

Anyway, First element in row is primary key of table.
Here is the gist

https://gist.github.com/v920749/4eb0568d51cac42316cd

Regards

*Amit Nagpal*
IT Consultant
Shah Satnam Ji Research & Development Foundation.
Sirsa

**Comment by mjaschen** [comment]
Hi,

I created a quick test and it gives me a total length of about 142 kilometres.

This script:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$polyline = new \Location\Polyline();

$fh = fopen('gps_track.csv', 'r');

while (($data = fgetcsv($fh, 1000, "\t")) !== false) {
    if (is_null($data[0]) || is_null($data[1])) {
        continue;
    }
    $polyline->addPoint(new \Location\Coordinate($data[0], $data[1]));
}

fclose($fh);

printf("Number of points in track...%d\n", $polyline->getNumberOfPoints());
printf("Length of track.............%0.3f m\n", $polyline->getLength(new \Location\Distance\Vincenty()));
```

produces this output:

```
% php polyline_distance.php
Number of points in track...859
Length of track.............142181.131 m
```


Here ist the [test data](https://gist.github.com/mjaschen/cae2fab52a33e52b0eb0) (it's exactly your CSV but with the first column removed).

**Comment by v920749** [comment]
Used the same code on my machine.

Number of points in track...859
Length of track.............97202.686 m

Can you point out any server dependency or precision setting. This might
not be an issue of your library but still if you can provide any inputs.




Regards

*Amit Nagpal*
IT Consultant
Shah Satnam Ji Research & Development Foundation.
Sirsa
+91.822.209.7787
-- Like a shadow, I am and I am not.

**Comment by v920749** [comment]
It's a debian 7 64 Bit, Lighttpd, Php5-FPM server.

Regards

*Amit Nagpal*
IT Consultant
Shah Satnam Ji Research & Development Foundation.
Sirsa
+91.822.209.7787
-- Like a shadow, I am and I am not.

**Comment by mjaschen** [comment]
Hi,

I'm using PHP 5.5 on OS X and different Linux systems:

```
% php -v
PHP 5.5.22 (cli) (built: Feb 19 2015 21:35:13)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

[Here are my PHP settings](https://gist.github.com/mjaschen/32865ffb8bb8e5c41a45) generated with `php -i`.

Maybe you can create a diff with your PHP settings to get a hint why your result is wrong.

Marcus

**Comment by v920749** [comment]
Thanks a lot, Issue is resolved now.
