### ISSUE TITLE
Error:  Call to a member function 

### ISSUE THREAD

**Issue by bivilbi** [mjaschen/phpgeo#55]
Good afternoon.
Put through composer require mjaschen/phpgeo (php 7.2).
I try to use an example from the description

`<?php
use Location\Bearing\BearingEllipsoidal;
use Location\Bearing\BearingSpherical;
use Location\Coordinate;
use Location\Formatter\Coordinate\DecimalDegrees;

$berlin = new Coordinate(52.5, 13.5);

$bearingSpherical = new BearingSpherical();
$bearingEllipsoidal = new BearingEllipsoidal();

$destination1 = $BearingSpherical->calculateDestination($berlin, 153, 56100);
$destination2 = $bearingEllipsoidal->calculateDestination($berlin, 153, 56100);

echo "Spherical:   " . $destination1->format(new DecimalDegrees()) . PHP_EOL;
echo "Ellipsoidal: " . $destination2->format(new DecimalDegrees()) . PHP_EOL;
`

I receive an error.
Uncaught Error: Call to a member function calculateDestination() on null in ...

But all other functions work.
What could be wrong?
Thanks.

**Comment by mjaschen** [comment]
Hi,

``` php
$bearingSpherical = new BearingSpherical();
$bearingEllipsoidal = new BearingEllipsoidal();

$destination1 = $BearingSpherical->calculateDestination($berlin, 153, 56100);
$destination2 = $bearingEllipsoidal->calculateDestination($berlin, 153, 56100);
```

In the line

``` php
$bearingSpherical = new BearingSpherical();
```

an instance named `$bearingSpherical` is created (name begins with `b`), while in

``` php
$destination1 = $BearingSpherical->calculateDestination($berlin, 153, 56100);
```

the instance name begins with a captial letter `B`.

Probably the problem vanishes after fixing the name.

**Comment by bivilbi** [comment]
That's right! Thanks!
