### ISSUE TITLE
It doesn't support multipolygon ?

### ISSUE THREAD

**Issue by sakjain02** [mjaschen/phpgeo#67]
I need any solution very urgently. Any help ?

**Comment by mjaschen** [comment]
Do you mean multipolygon in the sense of multiple nested polygons? If so, the answer is no. But depending on what you're trying to achieve it might be possible to implement a workaround. That would need more information though.

**Comment by sakjain02** [comment]
Yes, multiple nested polygons. I tried with running the loop like this
$district->coordinates = District coordinates 
[[[-73.5274147442424, 45.5235135910537], [-73.5267405150566, 45.5213507542707], [-73.526730736973, 45.5213191055823], [-73.5251840405205, 45.5163154069544], [-73.5211180482388, 45.5030087982047], [-73.5210609494464, 45.5028218537556], [-73.519588766187, 45.4980232821208], [-73.5190996853698, 45.4964289566497], [-73.5195781659101, 45.4963343047309], [-73.5196839019088, 45.4963133966792], [-73.5194596725416, 45.4957589853357], [-73.5194198324477, 45.4956604528783], [-73.5192457637265, 45.4952300445512], [-73.5192316055091, 45.4951826206437], [-73.5201799786231, 45.4955270226986], [-73.5206384853745, 45.4956935190374], [-73.5207829717662, 45.4957459753534], [-73.5209725353637, 45.4957996668035], [-73.5235780132462, 45.4965380018334], [-73.5262219855313, 45.4982100373889], [-73.5284680362731, 45.4999489748907], [-73.5298469696156, 45.5015420394985], [-73.5305050225488, 45.5047999722322], [-73.5303685029618, 45.5059606454643], [-73.5303612887981, 45.5060218456746], [-73.5303136916825, 45.5064264662076], [-73.530303899096, 45.5065098005189], [-73.5301920008631, 45.5074609662696], [-73.5299837760419, 45.5079099902282], [-73.529947196095, 45.5079888700974], [-73.5299324712868, 45.5080206302894], [-73.5298421739313, 45.5082153824715], [-73.5290672744326, 45.5098867509888], [-73.52856208026, 45.5109763322583], [-73.5284829714113, 45.5111469746062], [-73.5286487542914, 45.5129687164611], [-73.528911018503, 45.5158509714195], [-73.5294554693948, 45.5211335984265], [-73.5295139475797, 45.5217009757209], [-73.5292165563615, 45.5219837189258], [-73.5290279666459, 45.5221630331327], [-73.5283209856822, 45.5217839811147], [-73.5275250227419, 45.5218729979917], [-73.5275618647968, 45.5220460445442], [-73.5282439522962, 45.5252489880641], [-73.5279952745953, 45.5254416329282], [-73.5274147442424, 45.5235135910537]]]

$insidePoint = new Coordinate(45.52724046101783,-73.552116304636);
$polygons = json_decode($district->coordinates);
                foreach ($polygons as $polygon) {
                    $geofence = new Polygon();
                    foreach ($polygon as $point) {
                        $geofence->addPoint(new Coordinate($point[1],$point[0]));
                    }
                    if ($geofence->contains($insidePoint)) {
                        return $district;
                    }
                }
It doesn't found $insidePoint in the multipolygon coordinates which is district coordinates.
Something wrong here?

**Comment by sakjain02** [comment]
I have figured it out code is working but district coordinates are not correct is there any way to get coordinates of district online?

**Comment by sakjain02** [comment]
Thank you for answering. Problem is solved now
