### ISSUE TITLE
Feature: Simplify Polygon

### ISSUE THREAD

**Issue by csimpi** [mjaschen/phpgeo#69]
Why can't I simplify Polygon, but I can PolyLine?

**Comment by mjaschen** [comment]
Good point, that feature will be added!

**Comment by mjaschen** [comment]
You can now simplify polygons as well. Please use the `simplifyGeometry()` methods in `SimplifyBearing` and `SimplifyDouglasPeucker`.

In the next major release `simplify()` and `simplifyGeometry()` will be unified.
