### ISSUE TITLE
Calculate cardinal direction distances between two coordinates

### ISSUE THREAD

**Issue by LeoVie** [mjaschen/phpgeo#73]
Given you have two Coordinates:

- Point1 at (51.049531, 13.720699)
- Point2 at (51.069706, 13.775459)

you'd like to know the shortest possible right angle to reach the Point2 from Point1
![grafik](https://user-images.githubusercontent.com/7249788/94899084-f2ca1b80-0492-11eb-8aca-1372a1253d23.png)

This would be possible by determining the point in the NorthWest corner (Point3) and calculate the distances Point1<->Point3 and Point2<->Point3.

As the sortest possible distances should be calculated, there has to be a check before: If Point1 is in NorthWest of Point2, the shortest directions are to go south and east.

| Point1 in reference to Point2 | Directions  |
|-------------------------------|-------------|
| North                         | South       |
| East                          | West        |
| South                         | North       |
| West                          | East        |
| NorthWest                     | South, East |
| NorthEast                     | South, West |
| SouthWest                     | North, East |
| SouthEast                     | North, West |

The only real new logic would be this determination.
The determining of Point3 could be done via the class `Bounds`, the calculation of the distances via the class `Coordinate`.

What do you think about this feature? If something is unclear, please ask me. :)

**Comment by mjaschen** [comment]
That sounds like it's a useful feature which should be relatively easy to implement :-)

**Comment by LeoVie** [comment]
Nice, I'll implement it in the next days.
