### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by Hacktivista** [mjaschen/phpgeo#8]
I don't see the LICENSE file on your project, although composer.json indicates it's MIT. Please add it.

I see that you credit GPL licensed software, so maybe the license should be GPL.

**Comment by mjaschen** [comment]
Hi,

you're right, correct license information is currently missing. I'm doing some research now to find out what  the proper license is. AFAIK it will be GPL, because we're using GPL licensed code.

I'll add correct license information as soon as I've smartened up about the topic.

**Comment by mjaschen** [comment]
A short update: The next released version will be tagged with 1.0.0 and will be licensed under the GPL.

**Comment by mjaschen** [comment]
Added license information; tagged 1.0.0
